/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "isr_UART_RX.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "Pin_USR_LED_aliases.h"
#include "Pin_USR_LED.h"
#include "Pin_USR_SW1_aliases.h"
#include "Pin_USR_SW1.h"
#include "isr_USR_SW1.h"
#include "TIA_PD.h"
#include "ADC_SAR_PD.h"
#include "PinPD_K_aliases.h"
#include "PinPD_K.h"
#include "PinPD_A_aliases.h"
#include "PinPD_A.h"
#include "Pin_TIA_OUT_aliases.h"
#include "Pin_TIA_OUT.h"
#include "UART_IntClock.h"
#include "I2C_IntClock.h"
#include "ADC_SAR_PD_IRQ.h"
#include "ADC_SAR_PD_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

